### ISSUE TITLE
issue with the iparcelbox

### ISSUE THREAD

**Issue by supermarcie** [gadget-man/iparcelboxHA#1]
In all my integration items i see the message Translation Error: The intl string context ....

can someone help me with this

**Comment by gadget-man** [comment]
Can you post a screenshot of where you are seeing this, and confirm what version of HA you're using?

**Comment by supermarcie** [comment]
![image](https://user-images.githubusercontent.com/38017131/161926204-704912bb-0897-4a2a-8fbd-db0fd1c2dc92.png)

Version | core-2022.3.8
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.103-v8
CPU Architecture | aarch64
Timezone | Europe/Brussels

**Comment by gadget-man** [comment]
This seems to be an issue associated with localisation of the integration. We haven't localised it yet but are looking at doing so (contributions and PRs welcome!).

To confirm this to be the issue, could you set HA to English and check that it then loads OK?

**Comment by supermarcie** [comment]
do you mean changing the timezone?
because the language is english

**Comment by supermarcie** [comment]
just switched it to europe/London ==> but same issue
![image](https://user-images.githubusercontent.com/38017131/161990480-f22545f2-fbc5-427d-b988-8bf8f174f920.png)

**Comment by gadget-man** [comment]
OK - thanks for confirming. We'll look into this.

**Comment by supermarcie** [comment]
changed the language from English to Enlish(UK) and now the error is gone!
but still no information on all the sensors. ==> box was automatically found only had to enter the password

![image](https://user-images.githubusercontent.com/38017131/161996125-96380068-754c-491a-aecd-2e20d45b4fcb.png)

**Comment by gadget-man** [comment]
Ok that confirms it to be a localisation issue for sure. Please can you reboot your HA instance and send any relevant logs. If you have a battery powered iParcelBox, please make a pretend delivery first so that it’s full- this will keep it away whilst you refresh the connection.

**Comment by supermarcie** [comment]
I have a battery powered box, so i pretend a delivery.
I checked the logs and found out that he was checking the wrong IP adress.
So I made a static address in my router!
The error about that is gone.
The warning I have is the following 


Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 09:01:30 (5 occurrences)
Last logged: 09:01:30

Detected integration that accessed discovery_info['name'] instead of discovery_info.name; this will fail in version 2022.6. Please report issue to the custom component author for iparcelbox using this method at custom_components/iparcelbox/config_flow.py, line 175: _LOGGER.debug("iParcelBox device found via ZeroConf: %s", info["name"])
Detected integration that accessed discovery_info['host'] instead of discovery_info.host; this will fail in version 2022.6. Please report issue to the custom component author for iparcelbox using this method at custom_components/iparcelbox/config_flow.py, line 179: hostname = info["host"]
Detected integration that accessed discovery_info['properties'] instead of discovery_info.properties; this will fail in version 2022.6. Please report issue to the custom component author for iparcelbox using this method at custom_components/iparcelbox/config_flow.py, line 180: serial = info["properties"]["serial"]
Detected integration that accessed discovery_info['properties'] instead of discovery_info.properties; this will fail in version 2022.6. Please report issue to the custom component author for iparcelbox using this method at custom_components/iparcelbox/config_flow.py, line 181: mac = info["properties"]["mac"].upper()
Detected integration that accessed discovery_info['name'] instead of discovery_info.name; this will fail in version 2022.6. Please report issue to the custom component author for iparcelbox using this method at custom_components/iparcelbox/config_flow.py, line 182: name = info["name"].replace('._iparcelbox._tcp.local.', '')

But that is a warning no failure, so no clue were it goes wrong
below print screen of the device, it looks like he see the firmware version, but did not retrieve any sensor!

![image](https://user-images.githubusercontent.com/38017131/162383021-0a0f86f5-39af-464a-9bdc-3b8d7b4819d4.png)

**Comment by gadget-man** [comment]
Hi, thanks for this additional info. We aren't seeing those log alerts at our end. 

Please could you delete the device, then update your configuration.yaml as follows:
```
logger:
  default: error
    logs:
      custom_components.iparcelbox: debug

```
Please then reboot HA, add the discovered iParcelBox integration and enter your device password (with the iParcelBox 'full') and then post the [redacted] log here (or email direct to support@iparcelbox.com)

**Comment by supermarcie** [comment]
issue solved!
the standard address of home assistant was not correct.
Did a portforwarding from router to HA
