### ISSUE TITLE
Webhook error and all iParcelbox unknown.

### ISSUE THREAD

**Issue by Jaw0lf** [gadget-man/iparcelboxHA#9]
This error originated from a custom integration.

Logger: custom_components.iparcelbox
Source: custom_components/iparcelbox/__init__.py:148
integration: iParcelBox (documentation)
First occurred: 19:11:35 (2 occurrences)
Last logged: 20:07:58

Unable to create new webhook, may already exist

I am using Using latest version 0.0.17

I have removed the iParcelbox integration, deleted from HACS as well as ensuring the full folder is removed from custom components.
It had been working but stopped a month or 2 ago. Now moved my setup to a small factor PC and used cloudflare tunnel.
Restarted and reinstalled but still having this error.

You have helped me previously, so fingers crossed this time.

For info, if I go to iparcelbox in integrations it show 0.0.3 above custom integration.

**Comment by gadget-man** [comment]
Please can you turn on DEBUG logging for the iParcelBox integration, reboot HA then check the logs for any references to iParcelBox - you can email them directly to support@iparcelbox.com to avoid posting any potentially sensitive information here.

**Comment by Jaw0lf** [comment]
Thank you, email sent.

**Comment by gadget-man** [comment]
Closed as all HA functions working as expected - webhook being blocked on users machine, most likely a cloudflare / IP error.
